CREATE TABLE "user"
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    login      VARCHAR(255) NOT NULL,
    nickname   VARCHAR(255),
    birthday   TIMESTAMP
);
CREATE UNIQUE INDEX user_id_uindex
    ON "user" (id);

CREATE TABLE film
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- идентификатор целочисленный, автоинкрементный
    film_name     VARCHAR(255) NOT NULL,
    description   VARCHAR(200),
    releaseDate   TIMESTAMP,
    duration      INT
);
CREATE TABLE genre
(
    genre_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(64) NOT NULL
);

INSERT INTO genre (genre_name)
VALUES ('Комедия');
INSERT INTO genre (genre_name)
VALUES ('Драма');
INSERT INTO genre (genre_name)
VALUES ('Мультфильм');
INSERT INTO genre (genre_name)
VALUES ('Триллер');
INSERT INTO genre (genre_name)
VALUES ('Документальный');
INSERT INTO genre (genre_name)
VALUES ('Боевик');

CREATE TABLE mpa
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name  VARCHAR(64) NOT NULL
);

INSERT INTO mpa (mpa_name)
VALUES ('G');
INSERT INTO mpa (mpa_name)
VALUES ('PG');
INSERT INTO mpa (mpa_name)
VALUES ('PG-13');
INSERT INTO mpa (mpa_name)
VALUES ('R');
INSERT INTO mpa (mpa_name)
VALUES ('NC-17');

CREATE TABLE film_genre
(
    film_id   INT REFERENCES film(id),
    genre_id  INT REFERENCES genre(genre_id)
);

CREATE TABLE film_mpa
(
    film_id   INT REFERENCES film(id),
    mpa_id    INT REFERENCES mpa(id)
);

CREATE table likes
(
    film_id   INT REFERENCES film(id),
    user_id   INT REFERENCES "user"(id)
);

CREATE TABLE friends
(
    user_id    INT REFERENCES "user"(id),
    friend_id  INT REFERENCES "user"(id)
);